<a href="https://colab.research.google.com/github/2303a52211-byte/AI_Assi-a1/blob/main/assignment17.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Load the dataset assuming it's uploaded to the Colab environment
df = pd.read_csv("/content/shopping_trends.csv")

print("Original DataFrame head:")
display(df.head())
print("\nOriginal DataFrame info:")
df.info()

Original DataFrame head:

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually

Original DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               3900 non-null   int64
 1   Age                       3900 non-null   int64
 2   Gender                    3900 non-null   object
 3   Item Purchased            3900 non-null   object
 4   Category                  3900 non-null   object
 5   Purchase Amount (USD)     3900 non-null   int64
 6   Location                  3900 non-null   object
 7   Size                      3900 non-null   object
 8   Color                     3900 non-null   object
 9   Season                    3900 non-null   object
 10  Review Rating             3900 non-null   float64
 11  Subscription Status       3900 non-null   object
 12  Payment Method            3900 non-null   object
 13  Shipping Type             3900 non-null   object
 14  Discount Applied          3900 non-null   object
 15  Promo Code Used           3900 non-null   object
 16  Previous Purchases        3900 non-null   int64
 17  Preferred Payment Method  3900 non-null   object
 18  Frequency of Purchases    3900 non-null   object
dtypes: float64(1), int64(4), object(14)
memory usage: 579.0+ KB

2nd Question

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Load the dataset assuming it's uploaded to the Colab environment
df_sales = pd.read_csv("/content/sales_data.csv")

print("Original Sales DataFrame head:")
display(df_sales.head())
print("\nOriginal Sales DataFrame info:")
df_sales.info()

In [ ]:
# Convert 'Sale_Date' column to datetime format
df_sales['Sale_Date'] = pd.to_datetime(df_sales['Sale_Date'])

print("DataFrame info after Date conversion:")
df_sales.info()
display(df_sales.head())

In [ ]:
# Create new features: month, year, day of week
df_sales['Month'] = df_sales['Sale_Date'].dt.month
df_sales['Year'] = df_sales['Sale_Date'].dt.year
df_sales['DayOfWeek'] = df_sales['Sale_Date'].dt.dayofweek # Monday=0, Sunday=6

print("DataFrame head with new time-based features:")
display(df_sales.head())

In [ ]:
# Initialize MinMaxScaler
scaler = MinMaxScaler()

# Normalize the 'Sales_Amount' column
df_sales['Normalized_Sales'] = scaler.fit_transform(df_sales[['Sales_Amount']])

print("DataFrame head with Normalized Sales:")
display(df_sales.head())

In [ ]:
# Detect outliers using IQR method
Q1 = df_sales['Sales_Amount'].quantile(0.25)
Q3 = df_sales['Sales_Amount'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Lower bound for outliers: {lower_bound}")
print(f"Upper bound for outliers: {upper_bound}")

# Handle outliers by capping them
df_sales['Sales_Handled_Outliers'] = df_sales['Sales_Amount'].clip(lower=lower_bound, upper=upper_bound)

print("\nSales distribution before and after outlier handling:")
print("Original Sales min/max:", df_sales['Sales_Amount'].min(), df_sales['Sales_Amount'].max())
print("Outlier Handled Sales min/max:", df_sales['Sales_Handled_Outliers'].min(), df_sales['Sales_Handled_Outliers'].max())

display(df_sales.head())

In [2]:
# Check for missing values
print("Missing values before imputation:")
print(df[['Age', 'Purchase Amount (USD)', 'Location']].isnull().sum())

# Impute 'Age' with the median
df['Age'].fillna(df['Age'].median(), inplace=True)

# Impute 'Purchase Amount (USD)' with the median
df['Purchase Amount (USD)'].fillna(df['Purchase Amount (USD)'].median(), inplace=True)

# Impute 'Location' with the mode
df['Location'].fillna(df['Location'].mode()[0], inplace=True)

print("\nMissing values after imputation:")
print(df[['Age', 'Purchase Amount (USD)', 'Location']].isnull().sum())

Missing values before imputation:
Age                      0
Purchase Amount (USD)    0
Location                 0
dtype: int64

Missing values after imputation:
Age                      0
Purchase Amount (USD)    0
Location                 0
dtype: int64

/tmp/ipykernel_5135/2019011776.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)
/tmp/ipykernel_5135/2019011776.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Purchase Amount (USD)'].fillna(df['Purchase Amount (USD)'].median(), inplace=True)
/tmp/ipykernel_5135/2019011776.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Location'].fillna(df['Location'].mode()[0], inplace=True)

In [3]:
print(f"Number of rows before removing duplicates: {len(df)}")
df.drop_duplicates(inplace=True)
print(f"Number of rows after removing duplicates: {len(df)}")

Number of rows before removing duplicates: 3900
Number of rows after removing duplicates: 3900

In [4]:
df['Location'] = df['Location'].str.lower()
print("\nUnique locations after standardization:")
print(df['Location'].unique())

Unique locations after standardization:
['kentucky' 'maine' 'massachusetts' 'rhode island' 'oregon' 'wyoming'
 'montana' 'louisiana' 'west virginia' 'missouri' 'arkansas' 'hawaii'
 'delaware' 'new hampshire' 'new york' 'alabama' 'mississippi'
 'north carolina' 'california' 'oklahoma' 'florida' 'texas' 'nevada'
 'kansas' 'colorado' 'north dakota' 'illinois' 'indiana' 'arizona'
 'alaska' 'tennessee' 'ohio' 'new jersey' 'maryland' 'vermont'
 'new mexico' 'south carolina' 'idaho' 'pennsylvania' 'connecticut' 'utah'
 'virginia' 'georgia' 'nebraska' 'iowa' 'south dakota' 'minnesota'
 'washington' 'wisconsin' 'michigan']

In [5]:
# Encode 'Gender' and 'Location' using one-hot encoding
df = pd.get_dummies(df, columns=['Gender', 'Location'], drop_first=True)

print("\nCleaned DataFrame head after encoding:")
display(df.head())
print("\nCleaned DataFrame info after encoding:")
df.info()

Cleaned DataFrame head after encoding:

,Customer ID,Age,Item Purchased,Category,Purchase Amount (USD),Size,Color,Season,Review Rating,Subscription Status,...,Location_south dakota,Location_tennessee,Location_texas,Location_utah,Location_vermont,Location_virginia,Location_washington,Location_west virginia,Location_wisconsin,Location_wyoming
0,1,55,Blouse,Clothing,53,L,Gray,Winter,3.1,Yes,...,False,False,False,False,False,False,False,False,False,False
1,2,19,Sweater,Clothing,64,L,Maroon,Winter,3.1,Yes,...,False,False,False,False,False,False,False,False,False,False
2,3,50,Jeans,Clothing,73,S,Maroon,Spring,3.1,Yes,...,False,False,False,False,False,False,False,False,False,False
3,4,21,Sandals,Footwear,90,M,Maroon,Spring,3.5,Yes,...,False,False,False,False,False,False,False,False,False,False
4,5,45,Blouse,Clothing,49,M,Turquoise,Spring,2.7,Yes,...,False,False,False,False,False,False,False,False,False,False

Cleaned DataFrame info after encoding:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 67 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               3900 non-null   int64
 1   Age                       3900 non-null   int64
 2   Item Purchased            3900 non-null   object
 3   Category                  3900 non-null   object
 4   Purchase Amount (USD)     3900 non-null   int64
 5   Size                      3900 non-null   object
 6   Color                     3900 non-null   object
 7   Season                    3900 non-null   object
 8   Review Rating             3900 non-null   float64
 9   Subscription Status       3900 non-null   object
 10  Payment Method            3900 non-null   object
 11  Shipping Type             3900 non-null   object
 12  Discount Applied          3900 non-null   object
 13  Promo Code Used           3900 non-null   object
 14  Previous Purchases        3900 non-null   int64
 15  Preferred Payment Method  3900 non-null   object
 16  Frequency of Purchases    3900 non-null   object
 17  Gender_Male               3900 non-null   bool
 18  Location_alaska           3900 non-null   bool
 19  Location_arizona          3900 non-null   bool
 20  Location_arkansas         3900 non-null   bool
 21  Location_california       3900 non-null   bool
 22  Location_colorado         3900 non-null   bool
 23  Location_connecticut      3900 non-null   bool
 24  Location_delaware         3900 non-null   bool
 25  Location_florida          3900 non-null   bool
 26  Location_georgia          3900 non-null   bool
 27  Location_hawaii           3900 non-null   bool
 28  Location_idaho            3900 non-null   bool
 29  Location_illinois         3900 non-null   bool
 30  Location_indiana          3900 non-null   bool
 31  Location_iowa             3900 non-null   bool
 32  Location_kansas           3900 non-null   bool
 33  Location_kentucky         3900 non-null   bool
 34  Location_louisiana        3900 non-null   bool
 35  Location_maine            3900 non-null   bool
 36  Location_maryland         3900 non-null   bool
 37  Location_massachusetts    3900 non-null   bool
 38  Location_michigan         3900 non-null   bool
 39  Location_minnesota        3900 non-null   bool
 40  Location_mississippi      3900 non-null   bool
 41  Location_missouri         3900 non-null   bool
 42  Location_montana          3900 non-null   bool
 43  Location_nebraska         3900 non-null   bool
 44  Location_nevada           3900 non-null   bool
 45  Location_new hampshire    3900 non-null   bool
 46  Location_new jersey       3900 non-null   bool
 47  Location_new mexico       3900 non-null   bool
 48  Location_new york         3900 non-null   bool
 49  Location_north carolina   3900 non-null   bool
 50  Location_north dakota     3900 non-null   bool
 51  Location_ohio             3900 non-null   bool
 52  Location_oklahoma         3900 non-null   bool
 53  Location_oregon           3900 non-null   bool
 54  Location_pennsylvania     3900 non-null   bool
 55  Location_rhode island     3900 non-null   bool
 56  Location_south carolina   3900 non-null   bool
 57  Location_south dakota     3900 non-null   bool
 58  Location_tennessee        3900 non-null   bool
 59  Location_texas            3900 non-null   bool
 60  Location_utah             3900 non-null   bool
 61  Location_vermont          3900 non-null   bool
 62  Location_virginia         3900 non-null   bool
 63  Location_washington       3900 non-null   bool
 64  Location_west virginia    3900 non-null   bool
 65  Location_wisconsin        3900 non-null   bool
 66  Location_wyoming          3900 non-null   bool
dtypes: bool(50), float64(1), int64(4), object(12)
memory usage: 708.5+ KB

3rd question

In [34]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

# Load dataset
df = pd.read_csv("/content/dirty_v3_path.csv")

# -----------------------------
# STEP 1: HANDLE MISSING VALUES
# -----------------------------

# Numerical columns → fill with mean
num_cols = ['Age', 'Glucose', 'Blood Pressure']
for col in num_cols:
    df[col].fillna(df[col].mean(), inplace=True)

# Categorical columns → fill with mode
cat_cols = ['Gender', 'Medical Condition']
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

# -----------------------------
# STEP 2: REMOVE IRRELEVANT DATA
# -----------------------------

df.drop(['random_notes', 'noise_col'], axis=1, inplace=True)

# -----------------------------
# STEP 3: ENCODE CATEGORICAL DATA
# -----------------------------

le = LabelEncoder()

df['Gender'] = le.fit_transform(df['Gender'])
df['Medical Condition'] = le.fit_transform(df['Medical Condition'])

# -----------------------------
# STEP 4: FEATURE SCALING
# -----------------------------

scaler = StandardScaler()

numerical_cols = [
    'Age', 'Glucose', 'Blood Pressure', 'BMI',
    'Oxygen Saturation', 'Cholesterol', 'Triglycerides',
    'HbA1c', 'Physical Activity', 'Diet Score',
    'Stress Level', 'Sleep Hours'
]

df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

# -----------------------------
# STEP 5: SPLIT DATASET
# -----------------------------

# Target column (choose based on your goal)
# Here assuming 'Medical Condition' is target

X = df.drop('Medical Condition', axis=1)
y = df['Medical Condition']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -----------------------------
# STEP 6: SAVE CLEAN DATA
# -----------------------------

df.to_csv("processed_healthcare_dataset.csv", index=False)

# -----------------------------
# OUTPUT CHECK
# -----------------------------

print("Preprocessing Done ✅")
print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

/tmp/ipykernel_5135/3872691520.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)
/tmp/ipykernel_5135/3872691520.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

Preprocessing Done ✅
Train shape: (24000, 17)
Test shape: (6000, 17)

4th

In [36]:
###TASK 4
# Step 1: Import libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Step 2: Load dataset
data = pd.read_csv("/content/Employee_Salary_Dataset.csv")

print("Original Data:")
print(data.head())
print("\nShape before preprocessing:", data.shape)


# ----------------------------------
# Step 3: Handle Missing Values
# ----------------------------------

# Fill numerical columns with median
numerical_cols = data.select_dtypes(include=['int64', 'float64']).columns

for col in numerical_cols:
    data[col].fillna(data[col].median(), inplace=True)

# Fill categorical columns with mode
categorical_cols = data.select_dtypes(include=['object']).columns

for col in categorical_cols:
    data[col].fillna(data[col].mode()[0], inplace=True)


# ----------------------------------
# Step 4: Standardize Department Names
# ----------------------------------

if 'Department' in data.columns:
    data['Department'] = data['Department'].str.lower().str.strip()


# ----------------------------------
# Step 5: Detect & Remove Salary Outliers (IQR)
# ----------------------------------

# Assume salary column name
salary_col = None

for col in data.columns:
    if 'salary' in col.lower():
        salary_col = col
        break

if salary_col:
    Q1 = data[salary_col].quantile(0.25)
    Q3 = data[salary_col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    print(f"\nSalary Outlier Bounds: {lower_bound} to {upper_bound}")

    # Remove outliers
    data = data[(data[salary_col] >= lower_bound) & (data[salary_col] <= upper_bound)]


# ----------------------------------
# Step 6: Label Encoding
# ----------------------------------

le = LabelEncoder()

# Encode Department
if 'Department' in data.columns:
    data['Department'] = le.fit_transform(data['Department'])

# Encode Job Location (try common names)
location_col = None
for col in data.columns:
    if 'location' in col.lower():
        location_col = col
        break

if location_col:
    data[location_col] = le.fit_transform(data[location_col].astype(str))


# ----------------------------------
# Step 7: Final Output
# ----------------------------------

print("\nProcessed Data:")
print(data.head())

print("\nShape after preprocessing:", data.shape)

# Save cleaned dataset
data.to_csv("processed_employee_salary.csv", index=False)

print("\n✅ Preprocessing Completed. File saved as 'processed_employee_salary.csv'")

Original Data:
   ID  Experience_Years  Age  Gender  Salary
0   1                 5   28  Female  250000
1   2                 1   21    Male   50000
2   3                 3   23  Female  170000
3   4                 2   22    Male   25000
4   5                 1   17    Male   10000

Shape before preprocessing: (35, 5)

Salary Outlier Bounds: -4848750.0 to 8141250.0

Processed Data:
   ID  Experience_Years  Age  Gender  Salary
0   1                 5   28  Female  250000
1   2                 1   21    Male   50000
2   3                 3   23  Female  170000
3   4                 2   22    Male   25000
4   5                 1   17    Male   10000

Shape after preprocessing: (33, 5)

✅ Preprocessing Completed. File saved as 'processed_employee_salary.csv'

/tmp/ipykernel_5135/3759306594.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace=True)
/tmp/ipykernel_5135/3759306594.py:29: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].mode()[0], inplace=True)